# Generated by Django 4.2.1 on 2023-06-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produtocarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code_images'),
        ),
    ]
