# Generated by Django 4.2.1 on 2023-06-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_produto_qrcode_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='img',
            new_name='url',
        ),
    ]
