# Generated by Django 4.2.1 on 2023-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_img_produto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qrcode_image',
            field=models.ImageField(blank=True, upload_to='qr_code_images'),
        ),
    ]
