# Generated by Django 4.2.1 on 2023-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_produto_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code_images'),
        ),
    ]
